name: fnx_gallery
description: Easy to use AngularDart gallery component.
  Displays one big image with list of thumbnails bellow.
  Easily embedable into any AngularDart app.
version: 1.5.0
authors:
  - Tomucha <tomucha@gmail.com>
  - Honza Bittner <the@honzabittner.cz>
homepage: https://github.com/fnx-io/fnx_gallery

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  angular: ^6.0.1
  pedantic: ^1.0.0

dev_dependencies:
  build_runner: any
  build_web_compilers: any
