name: fnx_gallery
description: Easy to use AngularDart gallery component.
version: 0.0.7
authors:
  - Tomucha <tomucha@gmail.com>
  - Honza Bittner <the@honzabittner.cz>
homepage: https://github.com/fnx-io/fnx_gallery

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  angular2: '>=2.0.0 <= 2.2.0'
  browser: any

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
  intl_translation: any

transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: example/index.dart